In [1]:
%pip install numpy pandas matplotlib seaborn scikit-fuzzy scikit-learn >> /dev/null

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.load(
    "/Users/emre/GitHub/HU-AI/AIN421/dataset/raw/sepsis_dataset-2/dataset/dataset_full.npy"
)

In [4]:
print("Data Shape:", data.shape)
print("Data Type:", data.dtype)

print("Data Sample:")
print(data[0:5])

Data Shape: (36886, 24, 27)
Data Type: float64
Data Sample:
[[[ nan  nan  nan ...  nan  nan  nan]
  [118.  nan  nan ...   1.   0.   0.]
  [118. 165.  85. ...   0.   0.   0.]
  ...
  [115. 142.  80. ...   0.   0.   0.]
  [114. 179.  90. ...   0.   0.   0.]
  [117. 176.  98. ...   0.   0.   0.]]

 [[ nan  nan  nan ...  nan  nan  nan]
  [ nan  83.  36. ...   0.   0.   0.]
  [ 73.  80.  40. ...   0.   1.   0.]
  ...
  [ 75. 118.  64. ...   1.   0.   0.]
  [ 80. 115.  64. ...   1.   0.   0.]
  [ 80. 110.  63. ...   0.   0.   0.]]

 [[ nan  nan  nan ...  nan  nan  nan]
  [117. 118.  69. ...   0.   0.   0.]
  [122. 124.  70. ...   0.   0.   0.]
  ...
  [110. 140.  54. ...   1.   0.   0.]
  [113. 137.  85. ...   1.   0.   0.]
  [114. 149.  86. ...   1.   0.   0.]]

 [[ 65. 164.  73. ...   1.   0.   0.]
  [ 73. 145.  70. ...   1.   0.   0.]
  [ 93. 147.  76. ...   1.   0.   0.]
  ...
  [ 80. 153.  70. ...   0.   0.   0.]
  [ 74. 153.  56. ...   0.   0.   0.]
  [ 77. 135.  51. ...   0.   0.   0.

In [5]:
columns = [
    "patient_id",
    "heart_rate",
    "bp_systolic",
    "bp_diastolic",
    "map",
    "resp_rate",
    "temp",
    "spo2",
    "fio2",
    "wbc",
    "bun",
    "bilirubin",
    "creatinine",
    "lactate",
    "platelets",
    "ph",
    "pco2",
    "po2",
    "bicarbonate",
    "hemoglobin",
    "hematocrit",
    "potassium",
    "chloride",
    "gcs",
    "age",
    "sirs",
    "qsofa",
    "sepsis_icd",
]

In [7]:
# add patient id column to the data by repeating the patient id for each row to 24 hours
patient_ids = np.repeat(np.arange(data.shape[0]), 24)

data = np.hstack((patient_ids.reshape(-1, 1), data.reshape(-1, len(columns) - 1)))

In [8]:
print("Data Shape:", data.shape)
print("Data Sample:", data[0:5])

Data Shape: (885264, 28)
Data Sample: [[  0.                  nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan          nan          nan]
 [  0.         118.                  nan          nan          nan
   22.                  nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan          nan          nan  15.          35.48
    1.           0.           0.        ]
 [  0.         118.         165.          85.         103.
   15.          36.66666667          nan          nan          nan
           nan          nan          nan          nan          nan
           nan       

In [9]:
# convert data to pandas dataframe
data = pd.DataFrame(data, columns=columns)

In [10]:
data.head()

patient_id  heart_rate  bp_systolic  bp_diastolic    map  resp_rate  \
0         0.0         NaN          NaN           NaN    NaN        NaN   
1         0.0       118.0          NaN           NaN    NaN       22.0   
2         0.0       118.0        165.0          85.0  103.0       15.0   
3         0.0       110.0        119.0          64.0   76.0       15.0   
4         0.0       104.0        169.0          84.0  105.0       16.0   

        temp  spo2  fio2  wbc  ...  bicarbonate  hemoglobin  hematocrit  \
0        NaN   NaN   NaN  NaN  ...          NaN         NaN         NaN   
1        NaN   NaN   NaN  NaN  ...          NaN         NaN         NaN   
2  36.666667   NaN   NaN  NaN  ...          NaN         NaN         NaN   
3  36.666667   NaN   NaN  NaN  ...         17.0         NaN         NaN   
4  36.611111   NaN   NaN  NaN  ...         17.0         NaN         NaN   

   potassium  chloride   gcs    age  sirs  qsofa  sepsis_icd  
0        NaN       NaN   NaN    NaN   NaN    NaN         NaN  
1        NaN       NaN  15.0  35.48   1.0    0.0         0.0  
2        NaN       NaN  15.0  35.48   0.0    0.0         0.0  
3        4.2     110.0  15.0  35.48   0.0    0.0         0.0  
4        4.2     110.0  15.0  35.48   0.0    0.0         0.0  

[5 rows x 28 columns]

In [ ]:
# Selecting input features and output
input_features = [
    "heart_rate",
    "bp_systolic",
    "bp_diastolic",
    "map",
    "resp_rate",
    "temp",
    "spo2",
    "fio2",
    "wbc",
    "bun",
    "bilirubin",
    "creatinine",
    "lactate",
    "platelets",
    "ph",
    "pco2",
    "po2",
    "bicarbonate",
    "hemoglobin",
    "hematocrit",
    "potassium",
    "chloride",
    "gcs",
    "age",
    "sirs",
    "qsofa",
]

output_feature = ["sepsis_icd"]

# Selecting 500 instances for as a patient
data_selected = data[data["patient_id"] == 0]


X = data_selected[input_features]
y = data_selected[output_feature]

In [ ]:
# Check for missing values
print(data_selected.isnull().sum())

# Simple imputation (mean) for demonstration
X = X.fillna(X.mean())

NameError: name 'data_selected' is not defined

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
y = y.astype(int)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Correlation between inputs and output
corr_matrix = data_selected[input_features + [output_feature]].corr()
corr_with_output = corr_matrix[output_feature].drop(output_feature)
print(corr_with_output)

# Heatmap of correlations
plt.figure(figsize=(20, 15))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

ModuleNotFoundError: No module named 'scipy'

In [ ]:
# Separate data based on output
positive = data_selected[data_selected[output_feature] == 1]
negative = data_selected[data_selected[output_feature] == 0]

# Example: Histogram for 'heart_rate'
plt.figure(figsize=(10, 5))
sns.histplot(
    positive["heart_rate"],
    color="red",
    label="Sepsis",
    kde=True,
    stat="density",
    linewidth=0,
)
sns.histplot(
    negative["heart_rate"],
    color="blue",
    label="Non-Sepsis",
    kde=True,
    stat="density",
    linewidth=0,
)
plt.legend()
plt.title("Heart Rate Distribution")
plt.xlabel("Heart Rate")
plt.ylabel("Density")
plt.show()

In [ ]:
# Statistical summary
stats = data_selected[input_features].describe()
print(stats)

# Count of instances
count_positive = y.sum()
count_negative = len(y) - count_positive
print(f"Positive Instances: {count_positive}")
print(f"Negative Instances: {count_negative}")

In [ ]:
top_features = (
    corr_with_output.abs().sort_values(ascending=False).head(5).index.tolist()
)
print("Selected Features for FIS:", top_features)

In [ ]:
import numpy as np
import skfuzzy as fuzz

# Example for 'heart_rate'
heart_rate = X_scaled[:, input_features.index("heart_rate")]
heart_rate_universe = np.linspace(0, 1, 100)
heart_low = fuzz.trimf(heart_rate_universe, [0, 0, 0.5])
heart_medium = fuzz.trimf(heart_rate_universe, [0, 0.5, 1])
heart_high = fuzz.trimf(heart_rate_universe, [0.5, 1, 1])

# Repeat similar definitions for other inputs
# ...

In [ ]:
# Example rules
rules = [
    {
        "heart_rate": "high",
        "resp_rate": "high",
        "temp": "high",
        "wbc": "high",
        "lactate": "high",
        "sepsis": 1,
    },
    {
        "heart_rate": "low",
        "resp_rate": "low",
        "temp": "low",
        "wbc": "low",
        "lactate": "low",
        "sepsis": 0,
    },
    # Add more rules as needed
]

In [ ]:
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Define fuzzy variables
heart_rate_ctrl = ctrl.Antecedent(np.linspace(0, 1, 100), "heart_rate")
resp_rate_ctrl = ctrl.Antecedent(np.linspace(0, 1, 100), "resp_rate")
temp_ctrl = ctrl.Antecedent(np.linspace(0, 1, 100), "temp")
wbc_ctrl = ctrl.Antecedent(np.linspace(0, 1, 100), "wbc")
lactate_ctrl = ctrl.Antecedent(np.linspace(0, 1, 100), "lactate")
sepsis_ctrl = ctrl.Consequent(np.linspace(0, 1, 100), "sepsis")

# Membership functions
for var in [heart_rate_ctrl, resp_rate_ctrl, temp_ctrl, wbc_ctrl, lactate_ctrl]:
    var["low"] = fuzz.trimf(var.universe, [0, 0, 0.5])
    var["medium"] = fuzz.trimf(var.universe, [0, 0.5, 1])
    var["high"] = fuzz.trimf(var.universe, [0.5, 1, 1])

sepsis_ctrl["no"] = fuzz.trimf(sepsis_ctrl.universe, [0, 0, 0.5])
sepsis_ctrl["yes"] = fuzz.trimf(sepsis_ctrl.universe, [0.5, 1, 1])

# Define rules
rule1 = ctrl.Rule(
    heart_rate_ctrl["high"]
    & resp_rate_ctrl["high"]
    & temp_ctrl["high"]
    & wbc_ctrl["high"]
    & lactate_ctrl["high"],
    sepsis_ctrl["yes"],
)
rule2 = ctrl.Rule(
    heart_rate_ctrl["low"]
    & resp_rate_ctrl["low"]
    & temp_ctrl["low"]
    & wbc_ctrl["low"]
    & lactate_ctrl["low"],
    sepsis_ctrl["no"],
)
# Add more rules as per your design

# Create control system
sepsis_ctrl_system = ctrl.ControlSystem([rule1, rule2])  # Add all rules
sepsis_ctrl_sim = ctrl.ControlSystemSimulation(sepsis_ctrl_system)

In [ ]:
def predict_sepsis(sample):
    sepsis_ctrl_sim.input["heart_rate"] = sample[input_features.index("heart_rate")]
    sepsis_ctrl_sim.input["resp_rate"] = sample[input_features.index("resp_rate")]
    sepsis_ctrl_sim.input["temp"] = sample[input_features.index("temp")]
    sepsis_ctrl_sim.input["wbc"] = sample[input_features.index("wbc")]
    sepsis_ctrl_sim.input["lactate"] = sample[input_features.index("lactate")]

    # Compute the result
    sepsis_ctrl_sim.compute()
    return sepsis_ctrl_sim.output["sepsis"]

In [ ]:
predictions = []
for i in range(len(X_scaled)):
    sample = X_scaled[i]
    pred = predict_sepsis(sample)
    predictions.append(pred)

# Convert predictions to binary based on a threshold (e.g., 0.5)
y_pred = [1 if p > 0.5 else 0 for p in predictions]

In [ ]:
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve

# Confusion Matrix
cm = confusion_matrix(y, y_pred)
tn, fp, fn, tp = cm.ravel()

# Metrics
TPR = tp / (tp + fn)  # Sensitivity, Recall
FPR = fp / (fp + tn)
TNR = tn / (tn + fp)  # Specificity
FNR = fn / (fn + tp)
F1 = 2 * tp / (2 * tp + fp + fn)
ROC_AUC = roc_auc_score(y, predictions)

print("Confusion Matrix:")
print(cm)
print(f"TPR (Recall): {TPR:.2f}")
print(f"FPR: {FPR:.2f}")
print(f"TNR (Specificity): {TNR:.2f}")
print(f"FNR: {FNR:.2f}")
print(f"F1 Score: {F1:.2f}")
print(f"ROC AUC: {ROC_AUC:.2f}")

In [ ]:
fpr, tpr, thresholds = roc_curve(y, predictions)
plt.figure()
plt.plot(fpr, tpr, label="FIS (area = %0.2f)" % ROC_AUC)
plt.plot([0, 1], [0, 1], "k--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic (ROC) Curve")
plt.legend(loc="lower right")
plt.show()